CREATE TABLE video_pricing
    (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY,
        type VARCHAR(255) NOT NULL UNIQUE,
        price NUMERIC(20,2) NOT NULL,
        PRIMARY KEY(id)
    );

CREATE TABLE video_release
    (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR(255) NOT NULL UNIQUE,
        PRIMARY KEY(id)
    );

CREATE TABLE video_pricing_strategy
    (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY,
        release_name VARCHAR(255) NOT NULL,
        period_start INTEGER,
        period_end INTEGER,
        type VARCHAR(255) NOT NULL,
        charge VARCHAR(255) NOT NULL,
        PRIMARY KEY(id),
        CONSTRAINT FK_VIDEO_PRICING_STRATEGY_VIDE_PRICING_TYPE FOREIGN KEY (type) REFERENCES video_pricing(type),
        CONSTRAINT FK_VIDEO_PRICING_STRATEGY_VIDE_RELEASE FOREIGN KEY (release_name) REFERENCES video_release(name)
    );

CREATE TABLE video
    (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR(255) NOT NULL UNIQUE,
        release_name VARCHAR(255) NOT NULL,
        PRIMARY KEY(id),
        CONSTRAINT FK_VIDEO_VIDEO_RELEASE FOREIGN KEY (release_name) REFERENCES video_release(name)
    );

CREATE TABLE video_rent
    (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY,
        customer VARCHAR(255) NOT NULL,
        video_name VARCHAR(255) NOT NULL,
        rent_start_date TIMESTAMP NOT NULL,
        rent_end_date TIMESTAMP,
        paid_days INTEGER,
        PRIMARY KEY(id),
        CONSTRAINT FK_VIDEO_RENT_VIDEO FOREIGN KEY (video_name) REFERENCES video(name)
    );